### ISSUE TITLE
Error on installing via pip

### ISSUE THREAD

**Issue by onlygecko** [zblesk/csv-to-sqlite#1]
Hi,

I've tried to install csv-to-sqlite via pip but got the following error:

```python
Collecting csv-to-sqlite
  Using cached csv-to-sqlite-1.0.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4UwCvp/csv-to-sqlite/setup.py", line 6, in <module>
        with open(path.join(here, 'ReadMe.rst'), encoding='utf-8') as f:
      File "/usr/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-4UwCvp/csv-to-sqlite/ReadMe.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4UwCvp/csv-to-sqlite/
```

Installing the package manually worked fine:

```python
python setup.py install
```

Could You have a look in a spare minute?

**Comment by zblesk** [comment]
Hello, 

Seems to work fine for me. The only thing that seems off is that you're using Python 2.7 - I've only tested it for 3+. (I thought I'd tagged it as such on the PyPI package, but it might be possible there's a mistake - the web was non-cooperative at best. ) 

What OS are you running under?

If you're saying it works on 2.7 after manual install, it might be worth it to look into it when I have some free time. (Maybe the .rst file isn't getting bundled correctly.)

Thanks for the feedback.

**Comment by onlygecko** [comment]
That's it. I tried to install the package with Python 2.7 (without worrying if it's 2.7 compatible ). :-)

(I can't find that it's tagged for Python 3 - (https://pypi.python.org/pypi/csv-to-sqlite/1.0.1))
