### ISSUE TITLE
primary key

### ISSUE THREAD

**Issue by morinsb** [zblesk/csv-to-sqlite#10]
Is there a way to specify which column is a primary key and secondary key? I'm building a relational DB from the spreadsheets and need to establish the relationship.

**Comment by zblesk** [comment]
No, there is none. 
As far as I know, SQLite [doesn't let you](https://www.sqlite.org/faq.html#q11) add foreign keys to existing tables, either. Depending on the size of your files, maybe you could just write your queries without them.

Implementing any automated mechanism for this properly would be quite complicated, I think.
