### ISSUE TITLE
failure in importing CSV files with no UTF-8 characters

### ISSUE THREAD

**Issue by thecalle** [zblesk/csv-to-sqlite#12]
If CSV file contains no UTF-8 chars, import fails.

The problem is related to fixed file encoding open.

> self.csvfile = open(self.path, encoding="**utf8**") 

The solution is to change to:

> self.csvfile = open(self.path, encoding="**latin-1**") 

Can try to autoswitch in case of failure or BETTER a command line option to choose the file encoding format? In Europe is a common issue.

**Comment by zblesk** [comment]
I'll try to add an option when I find a bit of free time.

-------- Original Message --------

**Comment by zblesk** [comment]
Had some trouble making a file that would cause the failure. A sample would've been helpful. :D 

The next version will have an `--encoding` option.

**Comment by thecalle** [comment]
I tested the code with the new options and it work flawlessly!
I imported a file with Russian and Turkish terms and it worked using the new option.
Thanks a lot.
