### ISSUE TITLE
Feature request: Output the SQL, not the .sqlite database.

### ISSUE THREAD

**Issue by virtadpt** [zblesk/csv-to-sqlite#16]
Use case: I'm using rqlite (https://github.com/rqlite/rqlite) to query and analyze data sets in an automated fashion.  The thing is, rqlite won't open plain old SQLite databases as its own, it always requires the data to be loaded in from scratch.  One of the possible definitions of "from scratch" is "from a SQL dump out of a .sqlite database."

Thus, would it be possible to add a feature to csv-to-sqlite that doesn't output a .sqlite database, but the SQL statements that would be used to build the database in the first place?  That way, it could then be piped into an rqlite cluster through the usual methods.

**Comment by zblesk** [comment]
Csv-to-sqlite currently doesn't generate the sql statements for each record, so it's not just a matter of dumping them to a file, or something. And my feeling is adding this special case would bloat the script significantly, relatively to its tiny size. I'm not sure I'd want to add this, but I know I won't have the time to spend on it at the moment, even if I did. Sorry about that.

**Comment by virtadpt** [comment]
It's okay, I was just wondering.  I've got a second workflow that can do the same thing.  Thank you for responding.
