### ISSUE TITLE
Incorrect number of bindings supplied. The current statement uses 24, and there are 25 supplied.

### ISSUE THREAD

**Issue by ilovetogetspamed** [zblesk/csv-to-sqlite#20]
got this message while attempting to create db.  csv-to-sqlite -f {infile} -o {outfile}, any thoughts?  Thank you.

osx, python 3.8.7

**Comment by zblesk** [comment]
Can you provide a small sample file that causes this error?

**Comment by ilovetogetspamed** [comment]
I determined it to be the way the csv file was being opened.  It was a utf-8 file, so the open() method needs to have encoding='utf-8' set in it.  e.g.

open('sample.csv', 'r', encoding='utf-8', newline='') as csvfile:
	pass

**Comment by zblesk** [comment]
Ok, so that solves the problem? 
Interesting though, because 'utf8' _is_ the default encoding.

**Comment by ilovetogetspamed** [comment]
No, it didn't resolve it.  Problem seems to be in Sqlite component.

I tried importing it directly using sqlite3 cli interface:

sqlite> .mode csv
sqlite> .import sample.csv sample
sample.csv:50: unescaped " character
sample.csv:50: unterminated "-quoted field
sqlite> 

so there's something that is not being escaped properly in sqlite.  I didn't have time to dig into it further last night.

**Comment by ilovetogetspamed** [comment]
I was able to import sample.csv using Jetbrains' DataGrid product, which is built in to Jetbrains' Pycharm Professional.

it converted 'Status_v2' values to null in rows 14, 25 and 46, all 'Errors' values to null.

That maybe where the code is failing.

**Comment by zblesk** [comment]
"unescaped character" and "unterminated quoted field" make it sound like the error is actually in your input file (which is malformed); My guess is that instead of just failing, PyCharm discarded your invalid records and moved on.

**Comment by ilovetogetspamed** [comment]
That's very possible.  I wasn't criticizing, just giving you info.

**Comment by zblesk** [comment]
Sure, I didn't read that as criticism - I'm just trying to figure out if this is a bug here, or just malformed input data. 
As it seems to be the latter, I will close this issue. 
In case you're still struggling with that issue, maybe you could check it manually in a text editor and see if it's fixable by hand, if the file isn't too big.

**Comment by ilovetogetspamed** [comment]
The original source file is about 750 rows.
I don't mind missing a few rows, they aren't that important for this part of the project.

Thanks
