### ISSUE TITLE
How many columns can the script handle? I get `too many columns on [filename]` error

### ISSUE THREAD

**Issue by atav32** [zblesk/csv-to-sqlite#23]
I have a CSV with 998 columns and I get an error when I run `csv-to-sqlite -f many_columns.csv`

**Comment by zblesk** [comment]
Hello, 
I never checked. The script itself doesn't impose any limits on column count, just passes it to SQLite. It's configurable in SQLite in compile-time, so that basically means it's whatever the `sqlite3` package uses. 

Do you have something more specific than "I got an error"?
