### ISSUE TITLE
Run csv-to-sqlite from another python script?

### ISSUE THREAD

**Issue by Dunaway-Group-LLC** [zblesk/csv-to-sqlite#7]
I want to execute csv-to-sqlite as though it's a function.
Tried import and then subprocess.call - no luck
Any known way to do it?

**Comment by zblesk** [comment]
Hadn't tried this before. Will look into it.

**Comment by KyleKing** [comment]
I have the same problem! Here are two possible ways that might be of interest. Let me know if like `option 1` and I can test and prep a pull request (in theory I think it should work). I'm currently using `option 2` for now

---

1. Refactor to split the CLI parsing and db-creation functionality. Create a new method `create_db()` with all of the code logic from `start()`. `start()` then calls `create_db()` with the parsed CLI arguments (haven't tested, but I think this might work)

```py
@click.command()
@click.option("--file", "-f",
#...etc
def start(file, output, typing, drop_tables, verbose, delimiter):
    """A script that processes the input CSV files and copies them into a SQLite database.
    Each file is copied into a separate table. Column names are taken from the headers (first row) in the csv file.
    If file names are passed both via the --file option and standard input, all of them are processed.
    For example in PowerShell, if you want to copy all the csv files in the current folder
    into a database called "out.db", type:
        ls *.csv | % FullName | csv-to-sqlite -o out.db
    """
   create_db(file, output, typing, drop_tables, verbose, delimiter)

def create_db(file, output, typing='quick', drop_tables=False, verbose=False, delimiter=','):
    """Create the SQLite database based on the specified CSV files."""
    write_out.verbose = verbose
    files = list(file)
    if not sys.stdin.isatty():
        files.extend(list(sys.stdin))

        #...etc

if __name__ == "__main__":
    start()
```

Then the CLI would be unchanged, but the functionality could now be imported as a module by specifying args

```py
import csv_to_sqlite
csv_to_sqlit.create_db(file, output, typing, drop_tables, verbose, delimiter)
```

---

2. Alternatively, without changing `csvs-to-sqlite`, run the CLI with `doit` ([docs (link)](http://pydoit.org/index.html) - Python3-only). Sample script below. DoIt is just Python, so you can use glob, os, and other modules as needed. Note: `show_cmd` is a useful pattern for debugging, but isn't necessary.

```py
"""Save as `dodo.py`; `pip install doit`; `pip install csvs-to-sqlite`; run with `doit run createDBs`"""

from pathlib import Path


def show_cmd(task):
    """For debugging, log the full command to the console.

    task -- task dictionary passed by DoIt

    """
    return '{} > [{}\n]\n'.format(task.name, ''.join(['\n\t{}'.format(act) for act in task.actions]))


def task_createDBs():
    """Wrap the csvs-to-sqlite CLI. Create databases based on the matched pattern"""
    actions = []
    for srcCSV in Path.cwd().glob('*.csv'):
        outDB = Path('{}/{}.db'.format(srcCSV.parents[0], str(srcCSV.name).split('.')[0]))
        actions.append('poetry run csvs-to-sqlite "{}" "{}" --replace-tables '.format(srcCSV, outDB))

    return {
        'actions': actions,
        'title': show_cmd,
        'verbosity': 2,
    }
```

**Comment by nachovoss** [comment]
Could you further explain the process of using inside a script, thanks!

**Comment by zblesk** [comment]
As KyleKing mentioned, it was possible to do this before. 
However, the next version will make this easier.
